[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
dotenvy = "0.15.7"
hex = "0.4.3"
insta = "1.39.0"
merkle_proof = { git = "https://github.com/sigp/lighthouse.git", branch = "stable" }
primitive-types = "0.12.2"
prost = "0.13.1"
prost-build = "0.13.1"
prost-types = "0.13.1"
prost-wkt-types = "0.6.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_derive = "1.0.208"
serde_json = "=1.0.1"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.0"
tonic-build = "0.12.0"
tree_hash = "0.6.0"
types = { git = "https://github.com/sigp/lighthouse.git", branch = "stable" }

[profile.dev.build-override]
opt-level = 3
codegen-units = 1

[profile.release.build-override]
opt-level = 3
codegen-units = 1
