[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
insta = "1.39.0"
merkle_proof = { git = "https://github.com/sigp/lighthouse.git", branch = "stable" }
primitive-types = "0.12.2"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "=1.0.1"
tree_hash = "0.6.0"
types = { git = "https://github.com/sigp/lighthouse.git", branch = "stable" }

[profile.dev.build-override]
opt-level = 3
codegen-units = 1

[profile.release.build-override]
opt-level = 3
codegen-units = 1
