[package]
name = "headstate-proof-spike"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[lib]
name = "headstate_proof_spike"
path = "src/lib.rs"

[dependencies]
types = { git = "https://github.com/semiotic-ai/lighthouse.git", branch = "stable" }
primitive-types = "0.12.2"
serde = { version = "1.0", features = ["derive"] }
tree_hash = "0.6.0"
merkle_proof = { git = "https://github.com/suchapalaver/lighthouse.git", branch = "stable" }

[dev-dependencies]
insta = "1.39.0"
serde_json = "1.0"

