[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
alloy-primitives = "0.8.15"
alloy-consensus = "0.8.3"
alloy-eip2930 = "0.1.0"
alloy-rlp = "0.3.10"
base64 = "0.22.1"
bincode = "1.3.3"
clap = { version = "4.5.23", features = ["derive"] }
criterion = { version = "0.5.1", features = ["html_reports"] }
ethportal-api = { git = "https://github.com/ethereum/trin.git", version = "0.4.0" }
firehose-protos = { path = "crates/firehose-protos", version = "0.1.0" }
firehose-rs = { git = "https://github.com/semiotic-ai/firehose-rs.git", branch = "main" }
decoder = { path = "crates/decoder", version = "0.1.0" }
header-accumulator = { path = "crates/header-accumulator", version = "0.1.0" }
prost = "0.13.4"
prost-build = "0.13.4"
prost-wkt = "0.6.0"
prost-wkt-types = "0.6.0"
rand = "0.8.5"
reth-primitives = { git = "https://github.com/paradigmxyz/reth", version = "1.1.4" }
serde = "1.0.216"
serde_json = "1.0.133"
tempfile = "3.14.0"
thiserror = "2.0.8"
tokio = "1.42.0"
tonic = "0.12.3"
tonic-build = "0.12.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tree_hash = "0.8.0"
trin-validation = { git = "https://github.com/ethereum/trin.git", version = "0.1.0" }
zstd = "0.13.2"

[profile.dev.build-override]
opt-level = 3
codegen-units = 1

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[profile.release]
codegen-units = 1
lto = false
