[package]
name = "vee"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "vee"

[dependencies]
firehose-protos.workspace = true
flat-files-decoder.workspace = true
header-accumulator.workspace = true
